### PR TITLE
enable Brotli compression

### PR DESCRIPTION
**Pull request by sullis**
# Summary

Netty's HttpContentCompressor class has more than 1 constructor.

The zero arg constructor initializes the compressor object with "supportsCompressionOptions = false"

The alternate constructor:
```
HttpContentCompressor(CompressionOptions... compressionOptions)
```

will utilize Netty's StandardCompressionOptions to initialize Gzip, Deflate, and Brotli

```
        if (compressionOptions == null || compressionOptions.length == 0) {
            brotliOptions = Brotli.isAvailable() ? StandardCompressionOptions.brotli() : null;
            gzipOptions = StandardCompressionOptions.gzip();
            deflateOptions = StandardCompressionOptions.deflate();
            zstdOptions = Zstd.isAvailable() ? StandardCompressionOptions.zstd() : null;
        }
```

The alternate constructor will enable Brotli compression (if brotli4j is on the runtime classpath)

### CODE REVIEW

**Comment by spericas** [comment]
@sullis Please include rationale for using alternate constructor and and impact on options.

**Comment by sullis** [comment]
> @sullis Please include rationale for using alternate constructor and and impact on options.

I updated the PR description.

**Comment by sullis** [comment]
I added Brotli test cases in CompressionTest.java

cc: @hyperxpro

**Comment by sullis** [comment]
ready for review @spericas

**Comment by sullis** [comment]
This PR is ready for review.

**Pull request closed without merging**
