### PR TITLE
4.x: helidon-common sources JAR contains absolute paths #8761

### PR DESCRIPTION
**Pull request by jbescos**
### Description

https://github.com/helidon-io/helidon/issues/8761

### Documentation

N/A

### CODE REVIEW

**Comment by jbescos** [comment]
[helidon-common.zip](https://github.com/helidon-io/helidon/files/15320770/helidon-common.zip)
 
Generated jars

**Comment by jbescos** [comment]
Related to this:
Address maven 3.9.2 plugin issues (#7214)

**Comment by romain-grecourt** [comment]
> [helidon-common.zip](https://github.com/helidon-io/helidon/files/15320770/helidon-common.zip)
> 
> Generated jars

`Version.java` contains Maven properties in the string literals that need to be processed at build time.

```
unzip -p helidon-common/helidon-common-4.0.0-SNAPSHOT-sources.jar io/helidon/common/Version.java | grep '\$'
    public static final String VERSION = "${project.version}";
    public static final String REVISION = "${buildNumber}";
```

```
javap -v -cp helidon-common/helidon-common-4.0.0-SNAPSHOT.jar io.helidon.common.Version | grep '\$'
  #15 = String             #16            // ${project.version} ${buildNumber}
  #16 = Utf8               ${project.version} ${buildNumber}
  #26 = String             #27            // ${project.version}
  #27 = Utf8               ${project.version}
  #29 = String             #30            // ${buildNumber}
  #30 = Utf8               ${buildNumber}
    ConstantValue: String ${project.version}
    ConstantValue: String ${buildNumber}
         3: ldc           #15                 // String ${project.version} ${buildNumber}
```

**Comment by jbescos** [comment]
This is the output when it generates the sources jar:
```
[DEBUG] Configuring mojo execution 'org.apache.maven.plugins:maven-source-plugin:3.0.1:jar:default-cli' with basic configurator -->
[DEBUG]   (f) attach = true
[DEBUG]   (f) classifier = sources
[DEBUG]   (f) defaultManifestFile = /home/jbescos/workspace/helidon/common/common/target/classes/META-INF/MANIFEST.MF
[DEBUG]   (f) excludeResources = false
[DEBUG]   (f) finalName = helidon-common-4.0.0-SNAPSHOT
[DEBUG]   (f) forceCreation = false
[DEBUG]   (f) includePom = false
[DEBUG]   (f) outputDirectory = /home/jbescos/workspace/helidon/common/common/target
[DEBUG]   (f) project = MavenProject: io.helidon.common:helidon-common:4.0.0-SNAPSHOT @ /home/jbescos/workspace/helidon/common/common/pom.xml
[DEBUG]   (f) reactorProjects = [MavenProject: io.helidon.common:helidon-common:4.0.0-SNAPSHOT @ /home/jbescos/workspace/helidon/common/common/pom.xml]
[DEBUG]   (f) session = org.apache.maven.execution.MavenSession@4207609e
[DEBUG]   (f) skipSource = false
[DEBUG]   (f) useDefaultExcludes = true
[DEBUG]   (f) useDefaultManifestFile = false
[DEBUG] -- end configuration --
[DEBUG] isUp2date: false (Destination /home/jbescos/workspace/helidon/common/common/target/helidon-common-4.0.0-SNAPSHOT-sources.jar not found.)
[INFO] Building jar: /home/jbescos/workspace/helidon/common/common/target/helidon-common-4.0.0-SNAPSHOT-sources.jar
[DEBUG] adding directory META-INF/
[DEBUG] adding entry META-INF/MANIFEST.MF
[DEBUG] adding directory io/
[DEBUG] adding directory io/helidon/
[DEBUG] adding directory io/helidon/common/
[DEBUG] adding entry module-info.java
[DEBUG] adding entry io/helidon/common/package-info.java
[DEBUG] adding entry io/helidon/common/Weights.java
[DEBUG] adding entry io/helidon/common/LazyList.java
[DEBUG] adding entry io/helidon/common/Severity.java
[DEBUG] adding entry io/helidon/common/Weight.java
[DEBUG] adding entry io/helidon/common/Reflected.java
[DEBUG] adding entry io/helidon/common/Weighted.java
[DEBUG] adding entry io/helidon/common/Errors.java
[DEBUG] adding entry io/helidon/common/ParserHelper.java
[DEBUG] adding entry io/helidon/common/LazyValueImpl.java
[DEBUG] adding entry io/helidon/common/Generated.java
[DEBUG] adding entry io/helidon/common/Base64Value.java
[DEBUG] adding entry io/helidon/common/GenericType.java
[DEBUG] adding entry io/helidon/common/GenericTypeUtil.java
[DEBUG] adding entry io/helidon/common/LazyValue.java
[DEBUG] adding entry io/helidon/common/Builder.java
[DEBUG] adding entry io/helidon/common/SerializationConfig.java
[DEBUG] adding entry io/helidon/common/HelidonServiceLoader.java
[DEBUG] adding entry io/helidon/common/LazyListImpl.java
[DEBUG] adding entry io/helidon/common/NativeImageHelper.java
[DEBUG] adding directory META-INF/native-image/
[DEBUG] adding directory META-INF/native-image/io.helidon.common/
[DEBUG] adding directory META-INF/native-image/io.helidon.common/helidon-common/
[DEBUG] adding entry META-INF/native-image/io.helidon.common/helidon-common/resource-config.json
[DEBUG] adding directory /
[DEBUG] adding directory /home/
[DEBUG] adding directory /home/jbescos/
[DEBUG] adding directory /home/jbescos/workspace/
[DEBUG] adding directory /home/jbescos/workspace/helidon/
[DEBUG] adding directory /home/jbescos/workspace/helidon/common/
[DEBUG] adding directory /home/jbescos/workspace/helidon/common/common/
[DEBUG] adding directory /home/jbescos/workspace/helidon/common/common/target/
[DEBUG] adding directory /home/jbescos/workspace/helidon/common/common/target/generated-sources/
[DEBUG] adding directory /home/jbescos/workspace/helidon/common/common/target/generated-sources/templates/
[DEBUG] adding directory /home/jbescos/workspace/helidon/common/common/target/generated-sources/templates/io/
[DEBUG] adding directory /home/jbescos/workspace/helidon/common/common/target/generated-sources/templates/io/helidon/
[DEBUG] adding directory /home/jbescos/workspace/helidon/common/common/target/generated-sources/templates/io/helidon/common/
[DEBUG] adding entry /home/jbescos/workspace/helidon/common/common/target/generated-sources/templates/io/helidon/common/Version.java
[DEBUG] adding directory META-INF/maven/
[DEBUG] adding directory META-INF/maven/io.helidon.common/
[DEBUG] adding directory META-INF/maven/io.helidon.common/helidon-common/
[DEBUG] adding entry META-INF/maven/io.helidon.common/helidon-common/pom.xml
[DEBUG] adding entry META-INF/maven/io.helidon.common/helidon-common/pom.properties
```
I don't really see how to deal with this using the `build-helper-maven-plugin`.

**Comment by jbescos** [comment]
[helidon-common.zip](https://github.com/helidon-io/helidon/files/15329979/helidon-common.zip)

This looks good now.

**Review by romain-grecourt — APPROVED** [review]

**Pull request merged**
