### PR TITLE
OIDC updates

### PR DESCRIPTION
**Pull request by jmntn2000**
See issue #3590

### CODE REVIEW

**Comment by tomas-langer** [comment]
I will create new PRs for changes mentioned in this PR. I will separate these into two: required https for redirects and support for refresh cookie.

**Comment by tomas-langer** [comment]
see #4222

**Comment by romain-grecourt** [comment]
Closing as this has been fixed as part of #4222

**Comment by fssouza** [comment]
@romain-grecourt https://github.com/helidon-io/helidon/pull/4222 fixed the "https for redirects" but not the "support for refresh cookie". 
I think the support for refresh token is being discussed here https://github.com/helidon-io/helidon/issues/3590 

This are all the items included in this PR:
https://github.com/helidon-io/helidon/issues/3590#issuecomment-966732557

I believe the code in here might still be relevant (maybe a starting point) for this item:

> 1. Added server side refresh. If you are using cookies and server side OIDC provider you run into issues when the access token expires. All javascript related calls from the client will fail due to expired token and js calls for SPA will not redirect to lean on OIDC Provider for new tokens. To solve this I saved the refresh token encrypted in a separate cookie and when access token used for the request is expired I refresh it and update cookies so there is no disruption to the client (assuming refresh token is still valid).

**Pull request closed without merging**
