### PR TITLE
Remove trailing empty line in copyright comment (part 22)

### PR DESCRIPTION
**Pull request by Captain1653**
The next part of https://github.com/helidon-io/helidon/pull/5324 .

### CODE REVIEW

**Review by danielkec — APPROVED** [review]

**Comment by danielkec** [comment]
My `/trigger` kung-fu isn't strong enough, can @romain-grecourt try his?

**Comment by romain-grecourt** [comment]
The dojo wasn't working yesterday, no worries your kung-fu is very strong!

**Pull request merged**
