### PR TITLE
[4.x]: Change provided and optional to just optional - iteration 2 (#6495)

### PR DESCRIPTION
**Pull request by Captain1653**
Part of #6495

### CODE REVIEW

**Review by romain-grecourt — COMMENTED** [review]
Is it possible to group all the pom changes required to fix https://github.com/helidon-io/helidon/issues/6495 in this PR ?

**Comment by Captain1653** [comment]
Yes, it's possible.  I changed only 'helidon-config-metadata-processor' and I'm not sure about the others. A full list of modules would be extremely useful.

**Comment by romain-grecourt** [comment]
A simple text search of `<scope>provided</scope>` should be enough to list all the pom.xml files that need to be updated.

**Comment by Captain1653** [comment]
That's all. I didn't find any `<scope>provided</scope>` and `<optional>true</optional>` dependency.

**Review by romain-grecourt — DISMISSED** [review]

**Comment by Captain1653** [comment]
@romain-grecourt Approve it again, please. I fixed conflicts in  `nima/webclient/webclient/pom.xml`

**Review by romain-grecourt — APPROVED** [review]

**Pull request merged**
