### PR TITLE
MS SQL Server driver support for JPA/Hibernate in native image

### PR DESCRIPTION
**Pull request by Tomas-Kraus**
To run the tests, build Helidon and then execute:
```
cd <helidon_root>/tests/integration/jpa
mvn clean install -Dmssql -Pdocker -pl model,appl -Pnative-image -Dnative-image
```
```
Tests run: 16, Failures: 0, Errors: 0, Skipped: 0
```

### CODE REVIEW

**Comment by Tomas-Kraus** [comment]
@barchetta Please can you go trough PLS for MS SQL and get approval for it?

**Comment by Tomas-Kraus** [comment]
MS SQL integration test job passed. But I'll add another request to disable it. I just want to make sure it's fully implemented and works fine.

**Comment by Tomas-Kraus** [comment]
@barchetta Hi Joe, do we have any news about 3rd party approval for MS SQL?

**Comment by romain-grecourt** [comment]
closing for inactivity

**Pull request closed without merging**
