### PR TITLE
2.x: Upgrade checkout to v4, setup-java to v4.1.0

### PR DESCRIPTION
**Pull request by barchetta**
### Description

Upgrades GitHub actions:
* setup-java to v4.1.0
* checkout to v4

See #8435

### Documentation

No impact

### CODE REVIEW

**Review by romain-grecourt — APPROVED** [review]

**Review by senivam — APPROVED** [review]

**Comment by senivam** [comment]
Looks like newer JDK (Temurin) fails the build:
Previous:

image

proposed in the PR:

image

**Comment by senivam** [comment]
For my local build of the PR everything works just fine:
```
Apache Maven 3.9.5 (57804ffe001d7215b5e7bcb531cf83df38f93546)
Maven home: /home/mavines/software/maven/apache-maven-3.9.5
Java version: 11.0.22, vendor: Oracle Corporation, runtime: /media/storage/software/java/jdk-11.0.22
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "6.5.0-21-generic", arch: "amd64", family: "unix"
```

**Comment by barchetta** [comment]
The failing test is known to be unstable: #4323

**Comment by senivam** [comment]
To prove the issue is JDK related, I've done a tiny modification to your PR which is rolling back just one JDK version for the Helidon build:
image

Basically, the version of the action is not important, it does not relate to JDK's version, but they've just updated the Temurine JDK to 11.0.22. And I have to roll it back to the 11.0.21. After I did this the build just had passed OK:

image


Before the change it [was failing](https://github.com/senivam/helidon/actions/runs/8145782770) in my local branch as well. 

The reference to the passing action is https://github.com/senivam/helidon/actions/runs/8146385385
The reference to the code change is https://github.com/senivam/helidon/commit/5ee64e950b056a6c98322b1dbcb908adbb562115

**Comment by barchetta** [comment]
The test is unstable due to a race condition so the changing of the JDK is likely altering timing.  Looks like @danielkec fixed the race condition in 3.x but not 2.x. I've back ported the fix in #8453. Hopefully that resolves the problem!

**Pull request merged**
