### PR TITLE
Fix invalid example in se/config/advanced-configuration.adoc (#4775)

### PR DESCRIPTION
**Pull request by Captain1653**
Part of #4775 

I can backport it into 2.x and 4.x after merging if necessary. 

I've already signed OCA. It's an automation problem.

- [ ] Backport to 2.x
- [ ] Backport to 4.x

### CODE REVIEW

**Review by romain-grecourt — APPROVED** [review]

**Comment by Captain1653** [comment]
@romain-grecourt Can it be merged or we should wait for something?

**Comment by tjquinno** [comment]
@Captain1653 The ports to 2.x and 4.x will need to be in separate PRs; a single PR can merge only into one branch. 

I've added check boxes for each Helidon release to the issue so we can track the separate PRs there.

**Comment by Captain1653** [comment]
@tjquinno Thank you for your explanation. I was waiting for merging this PR. I'll create backports soon.

**Pull request merged**
