### PR TITLE
Use image with jdk20, install maven and add --enable-preview

### PR DESCRIPTION
**Pull request by klustria**

### CODE REVIEW

**Comment by klustria** [comment]
Current Dockerfile generates this and will fail because JDK version is wrong:
```
# 1st stage, build the app
FROM maven:3.8.4-openjdk-17-slim as build

WORKDIR /helidon

# Create a first layer to cache the "Maven World" in the local repository.
# Incremental docker builds will always resume after that, unless you update
# the pom
ADD pom.xml pom.xml
ADD client/pom.xml client/pom.xml
ADD server/pom.xml server/pom.xml
RUN mvn package -Dmaven.test.skip -Declipselink.weave.skip -DskipOpenApiGenerate

# Do the Maven build!
# Incremental docker builds will resume here when you change sources
ADD client/src client/src
ADD server/src server/src
ADD spec/api.yaml spec/api.yaml
RUN mvn package -DskipTests

RUN echo "done!"

# 2nd stage, build the runtime image
FROM openjdk:17-jdk-slim
WORKDIR /helidon

# Copy the binary built in the 1st stage
COPY --from=build /helidon/server/target/myproject-23-server.jar ./
COPY --from=build /helidon/server/target/libs ./libs

CMD ["java", "-jar", "myproject-23-server.jar"]

EXPOSE 8080
```

New generated Dockerfile will add the following
1. Use jdk20 image
2. Download maven
3. Add --enable-preview when running the app

```
# 1st stage, build the app
FROM container-registry.oracle.com/java/openjdk:20 as build

# Install maven
WORKDIR /usr/share
RUN set -x && \
    curl -O https://archive.apache.org/dist/maven/maven-3/3.8.4/binaries/apache-maven-3.8.4-bin.tar.gz && \
    tar -xvf apache-maven-*-bin.tar.gz  && \
    rm apache-maven-*-bin.tar.gz && \
    mv apache-maven-* maven && \
    ln -s /usr/share/maven/bin/mvn /bin/

WORKDIR /helidon

# Create a first layer to cache the "Maven World" in the local repository.
# Incremental docker builds will always resume after that, unless you update
# the pom
ADD pom.xml pom.xml
ADD client/pom.xml client/pom.xml
ADD server/pom.xml server/pom.xml
RUN mvn package -Dmaven.test.skip -Declipselink.weave.skip -DskipOpenApiGenerate

# Do the Maven build!
# Incremental docker builds will resume here when you change sources
ADD client/src client/src
ADD server/src server/src
ADD spec/api.yaml spec/api.yaml
RUN mvn package -DskipTests

RUN echo "done!"

# 2nd stage, build the runtime image
FROM container-registry.oracle.com/java/openjdk:20
WORKDIR /helidon

# Copy the binary built in the 1st stage
COPY --from=build /helidon/server/target/myproject-23-server.jar ./
COPY --from=build /helidon/server/target/libs ./libs

CMD ["java", "--enable-preview", "-jar", "myproject-23-server.jar"]

EXPOSE 8080
```

**Comment by romain-grecourt** [comment]
@klustria This should be updated to use JDK 21 instead of 20.

**Comment by klustria** [comment]
> @klustria This should be updated to use JDK 21 instead of 20.

@romain-grecourt ... FYI, unfortunately, OpenJDK 21 and JDK 21 are not available yet in https://container-registry.oracle.com/ so will just leave this PR hanging for now until v21 becomes available. Will ping you for review once it's available.

**Comment by klustria** [comment]
This PR is for issue https://github.com/helidon-io/helidon/issues/7180

**Comment by romain-grecourt** [comment]
> @romain-grecourt ... FYI, unfortunately, OpenJDK 21 and JDK 21 are not available yet in https://container-registry.oracle.com/ so will just leave this PR open for now until v21 becomes available. Will ping you for review once it's available.

See https://github.com/helidon-io/helidon/blob/fb7585c95be7a2c42b58d7ca36a2fd34c186aaba/examples/quickstarts/helidon-quickstart-se/Dockerfile#L18

**Comment by klustria** [comment]
> > @romain-grecourt ... FYI, unfortunately, OpenJDK 21 and JDK 21 are not available yet in https://container-registry.oracle.com/ so will just leave this PR open for now until v21 becomes available. Will ping you for review once it's available.
> 
> See
> 
> https://github.com/helidon-io/helidon/blob/fb7585c95be7a2c42b58d7ca36a2fd34c186aaba/examples/quickstarts/helidon-quickstart-se/Dockerfile#L18

Was this tested? It seems to fail for me when I pull from my local docker:
```
docker pull container-registry.oracle.com/java/openjdk:21
Error response from daemon: manifest for container-registry.oracle.com/java/openjdk:21 not found: manifest unknown: manifest unknown
```

**Comment by romain-grecourt** [comment]
You're right, I think this was not tested. CC @tomas-langer

**Comment by tomas-langer** [comment]
JDK 21 is not yet avialable, we cannot fix it for the time being. Same for native image.
Until releases are available, our dockerfiles cannot be used

**Comment by tomas-langer** [comment]
Closing this PR as it is no longer relevant (we use Java 21 and we do not need `--enable-preview`. Please kindly open a new one for Java 21 when possible

**Pull request closed without merging**
