### PR TITLE
Use Hamcrest assertions instead of JUnit in  dbclient/jdbc - backport2.x (#1749)

### PR DESCRIPTION
**Pull request by Captain1653**
Part of #1749 

I've already signed OCA. It's an automation problem.

[Original PR](https://github.com/helidon-io/helidon/pull/5038)

### CODE REVIEW

**Review by romain-grecourt — DISMISSED** [review]

**Comment by romain-grecourt** [comment]
There seems to be a bug in the changes that were made. The updated tests are consistently failing.

**Comment by Captain1653** [comment]
@romain-grecourt Thank you for your message. I was blind.
It should be `assertThat(collection, contains("item1", "item2"))`, but I used "assertThat(collection, contains(expectedCollection))".

Screenshot 2022-10-06 at 19 20 19

**Review by romain-grecourt — APPROVED** [review]

**Pull request merged**
