### PR TITLE
Support customize CustomizedEncodingContext in Http1ConnectionProvider

### PR DESCRIPTION
**Pull request by joeyleeeeeee97**

### CODE REVIEW

**Comment by joeyleeeeeee97** [comment]
@tomas-langer  Hi, please take a look

**Comment by joeyleeeeeee97** [comment]
@tomas-langer  @barchetta @spericas  Hi, please take a look

**Comment by spericas** [comment]
@joeyleeeeeee97 Could you please describe the use case for this content-encoding extension? In general, you can have multiple content encodings associated with a request/response.

**Comment by joeyleeeeeee97** [comment]
@spericas  Hi, I am trying to fix this TODO. 
```
// todo pass from server config
    private final ContentEncodingContext contentEncodingContext = ContentEncodingContext.create();
```
As described, we could pass context from config

**Pull request closed without merging**
