### PR TITLE
Use Hamcrest assertions instead of JUnit in common/common - backport helidon-2.x (#1749)

### PR DESCRIPTION
**Pull request by Captain1653**
Part of #1749 . 

Backport helidon-2.x, details can be found [here](https://github.com/oracle/helidon/issues/1749#issuecomment-1248512970) .

I've already signed OCA.

### CODE REVIEW

**Comment by Captain1653** [comment]
The build was green and then became red. Some tests failed, but I didn't touch them.
Screenshot 2022-09-19 at 22 57 57

**Comment by romain-grecourt** [comment]
The merge pipeline re-runs every time the target branch is updated. You got unlucky and ran into some intermittent test failures.

**Review by romain-grecourt — APPROVED** [review]

**Pull request merged**
