### PR TITLE
Use Hamcrest assertions instead of JUnit in  media/common - backport 2.x (#1749)

### PR DESCRIPTION
**Pull request by Captain1653**
Part of #1749 

I've already signed OCA. It's an automation problem.

[Original PR](https://github.com/helidon-io/helidon/pull/4999)

### CODE REVIEW

**Review by romain-grecourt — DISMISSED** [review]

**Comment by Captain1653** [comment]
I was wrong. Explanations can be found [here](https://github.com/helidon-io/helidon/pull/5039#issuecomment-1270372914)

**Review by romain-grecourt — APPROVED** [review]

**Pull request merged**
