### PR TITLE
Remove trailing empty line in copyright comment (part 17)

### PR DESCRIPTION
**Pull request by Captain1653**
The last part of https://github.com/helidon-io/helidon/pull/5324 .

P.S. There is some misunderstanding in my head.
There are no warnings in the log, but I can see empty lines in the code.
Screenshot 2023-01-03 at 23 01 16

Does the command `mvn validate  -Pcheckstyle` check all files? I run from the root folder.

### CODE REVIEW

**Comment by romain-grecourt** [comment]
Checkstyle does not validate the copyright. How about `mvn validate -Pcopyright` ?

**Comment by Captain1653** [comment]
Yes, I ment copyright. It's only typo in my message.

**Review by romain-grecourt — APPROVED** [review]

**Comment by Captain1653** [comment]
@romain-grecourt  Thank you, but I have the same result. It doesn't see other files.

**Comment by romain-grecourt** [comment]
It's a bug in the enforcer plugin, I'll file an issue for it.

The plugin discovers all files and then filters them using `.gitignore` ; the top-level `.gitignore` contains a line with `profile` and that excludes lines that contain the word `profile`.

E.g.
```bash
 mvn -f examples/pom.xml validate -Pcopyright -N -X | grep 'Excluding' | grep 'examples/microprofile' | grep 'SimpleAPIFilter'
[DEBUG] Excluding examples/microprofile/openapi-basic/src/main/java/io/helidon/microprofile/examples/openapi/basic/internal/SimpleAPIFilter.java
```

**Comment by romain-grecourt** [comment]
See https://github.com/helidon-io/helidon-build-tools/issues/839 CC @tomas-langer

**Pull request merged**
